systemNamespace: metacall-system
functionsNamespace: metacall-functions

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

runtime:
  imageRepository: localhost:5000/metacall/function

operator:
  replicas: 1
  image:
    repository: localhost:5000/metacall/function-mesh-operator
    tag: dev
    pullPolicy: IfNotPresent
  resources: {}

api:
  replicas: 1
  image:
    repository: localhost:5000/metacall/function-mesh-api
    tag: dev
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9000
  resources: {}

router:
  replicas: 1
  image:
    repository: localhost:5000/metacall/function-mesh-router
    tag: dev
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9090
  resources: {}

cilium:
  enabled: true
  hubble:
    enabled: true
    l7Visibility: false
