apiVersion: v1
kind: ServiceAccount
metadata:
  name: function-mesh-operator
  namespace: metacall-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: function-mesh-api
  namespace: metacall-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: function-mesh-router
  namespace: metacall-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: function-mesh-operator
rules:
  - apiGroups:
      - metacall.io
    resources:
      - functions
      - functions/status
      - functions/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: function-mesh-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: function-mesh-operator
subjects:
  - kind: ServiceAccount
    name: function-mesh-operator
    namespace: metacall-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: function-mesh-api
rules:
  - apiGroups:
      - metacall.io
    resources:
      - functions
      - functions/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: function-mesh-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: function-mesh-api
subjects:
  - kind: ServiceAccount
    name: function-mesh-api
    namespace: metacall-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: function-mesh-router
rules:
  - apiGroups:
      - metacall.io
    resources:
      - functions
      - functions/status
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: function-mesh-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: function-mesh-router
subjects:
  - kind: ServiceAccount
    name: function-mesh-router
    namespace: metacall-system
