apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tempo
spec:
  ports:
    - name: tempo-otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: tempo-otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: tempo-http
      port: 3100
      protocol: TCP
      targetPort: 3100
  selector:
    app.kubernetes.io/name: tempo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.6.1
          args:
            - "-config.file=/etc/tempo.yaml"
          ports:
            - containerPort: 3100
              name: tempo-http
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - mountPath: /etc/tempo.yaml
              name: tempo-config
              subPath: tempo.yaml
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100
    distributor:
      receivers:
        otlp:
          protocols:
            http:
            grpc:
    ingester:
      max_block_duration: 5m
    compactor:
      compaction:
        block_retention: 1h
    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: kind
      processor:
        local_blocks:
          filter_server_spans: false
        span_metrics: {}
    overrides:
      metrics_generator_processors: [span_metrics, service_graphs]
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
        wal:
          path: /tmp/tempo/wal
